### ISSUE TITLE
Add option to specify a path for the `package.json`-containing folder

### ISSUE THREAD

**Issue by eirikove** [glitch-txs/vite-size-action#2]
Hi!

I want to try this action out in a monorepo where the `package.json` file is not located in the root of the repo.

Github provide a `working-directory` option the `run` part of a workflow, so it would be great if you could add that as an input so I can use it like this:

```yml
- uses: glitch-txs/vite-size-action@1.0.0
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    working-directory: ./frontend
```

Some resources:

https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunworking-directory

https://stackoverflow.com/questions/58139175/running-actions-in-another-directory
